#!/usr/bin/env python3
"""Build js-dos bundles from the plain game directories in games/.

The bundles that originally shipped with this repo were bare zips of the game
folder. The vendored emulators runtime (0.73.x) expects a bundle that carries
its own metadata:

    .jsdos/dosbox.conf   full DOSBox config, including the [autoexec] that
                         mounts C: and starts the game
    .jsdos/readme.txt    printed by the autoexec; its absence breaks startup
    .jsdos/jsdos.json    bundle descriptor

Without those the runtime aborts with "Broken bundle, .jsdos/dosbox.conf not
found" and no game can start.

The templates in tools/jsdos-template/ were generated by js-dos itself
(`emulators.dosBundle()`), so the config is exactly what the runtime expects
rather than a hand-written approximation. Only the autoexec command is
substituted per game.

Run after changing a game's files or its startup command:

    python3 tools/build-jsdos-bundles.py
"""

import pathlib
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAMES_DIR = ROOT / "games"
TEMPLATE_DIR = pathlib.Path(__file__).resolve().parent / "jsdos-template"

GAMES = {
    "civ": {
        # CIV.BAT assumes an installed layout (`cd \mps\civ`), so call the
        # executable directly from the mounted bundle root instead.
        "command": "CIV.EXE",
        "title": "Sid Meier's Civilization",
    },
    "oregon": {
        "command": "OREGON.EXE",
        "title": "The Oregon Trail",
    },
}


def build(key: str, config: dict) -> None:
    src_dir = GAMES_DIR / key
    if not src_dir.is_dir():
        raise SystemExit(f"missing game directory: {src_dir}")

    command = config["command"]
    conf = (TEMPLATE_DIR / "dosbox.conf.tmpl").read_text().replace("{command}", command)
    descriptor = (TEMPLATE_DIR / "jsdos.json.tmpl").read_text().replace("{command}", command)
    readme = (TEMPLATE_DIR / "readme.txt").read_text()

    entry = src_dir / command
    if not entry.exists():
        raise SystemExit(f"{key}: autoexec command {command} not found in {src_dir}")

    files = sorted(p for p in src_dir.rglob("*") if p.is_file() and p.name != ".DS_Store")
    out_path = GAMES_DIR / f"{key}.jsdos"

    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as z:
        # The extractor creates directories from explicit directory entries.
        # Without this one, `.jsdos/dosbox.conf` never lands on the emulated
        # filesystem and DOSBox exits with code 101 before printing anything.
        dir_entry = zipfile.ZipInfo(".jsdos/")
        dir_entry.external_attr = (0o40755 << 16) | 0x10  # directory bit
        z.writestr(dir_entry, b"")

        z.writestr(".jsdos/dosbox.conf", conf)
        z.writestr(".jsdos/readme.txt", readme)
        z.writestr(".jsdos/jsdos.json", descriptor)
        for path in files:
            z.write(path, path.relative_to(src_dir).as_posix())

    size_kb = out_path.stat().st_size / 1024
    print(f"{out_path.relative_to(ROOT)}: {len(files)} files, autoexec={command}, {size_kb:.0f} KB")


def main() -> None:
    for key, config in GAMES.items():
        build(key, config)


if __name__ == "__main__":
    main()
